"""Tests for ``tools.linters.license_gate``.

These tests are hermetic: they parse fixture ``uv export`` output and assert on
the audited package set and the built ``pip-licenses`` command, rather than
shelling out to ``uv``/``pip-licenses``. The CI step invokes the same module
functions, so the scoping behaviour under test is the behaviour that runs.

AC-4 also has a reproducible *manual* step documented in the PR body (add a GPL
runtime dep, watch the gate go red, revert); the fixture-based test below makes
the same guarantee offline.
"""

from __future__ import annotations

from pathlib import Path

from tools.linters.license_gate import (
    FORBIDDEN_LICENSES,
    build_fail_on,
    build_pip_licenses_command,
    runtime_package_names,
)

# ---------------------------------------------------------------------------
# Fixtures: representative `uv export` output
# ---------------------------------------------------------------------------

# `uv export --frozen --no-dev --no-emit-project --no-hashes` for the current
# repo: runtime closure of [project].dependencies (httpx, rich, pydantic,
# pydantic-settings) — all permissive (MIT/BSD/Apache). No dev-group packages.
RUNTIME_EXPORT = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-dev --no-emit-project --no-hashes
annotated-types==0.7.0
    # via pydantic
anyio==4.13.0
    # via httpx
certifi==2026.4.22
    # via
    #   httpcore
    #   httpx
h11==0.16.0
    # via httpcore
httpcore==1.0.9
    # via httpx
httpx==0.28.1
    # via nsg-mes-harness
idna==3.13
    # via
    #   anyio
    #   httpx
markdown-it-py==4.0.0
    # via rich
mdurl==0.1.2
    # via markdown-it-py
pydantic==2.13.3
    # via
    #   nsg-mes-harness
    #   pydantic-settings
pydantic-core==2.46.3
    # via pydantic
pydantic-settings==2.14.0
    # via nsg-mes-harness
pygments==2.20.0
    # via rich
python-dotenv==1.2.2
    # via pydantic-settings
rich==15.0.0
    # via nsg-mes-harness
sniffio==1.3.1
    # via anyio
typing-extensions==4.15.0
    # via pydantic
"""

# Dev-group tools (ruff/mypy/pytest/yamllint) that appear ONLY without
# `--no-dev`. The gate must never see these.
DEV_ONLY_NAMES = ("pytest", "ruff", "mypy", "respx", "yamllint", "pytest-asyncio")

# Hypothetical export where a RUNTIME dependency carries a copyleft license
# (the package name is what matters here; license is asserted via the gate).
RUNTIME_EXPORT_WITH_COPYLEFT = RUNTIME_EXPORT + """\
chardet==5.2.0
    # via nsg-mes-harness
"""


def _repo_root() -> Path:
    # tests/ -> linters/ -> tools/ -> repo root
    return Path(__file__).resolve().parents[3]


def _ci_yaml() -> str:
    return (_repo_root() / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# AC-1: gate is green when no runtime dependency is copyleft (current repo)
# ---------------------------------------------------------------------------


def test_ac1_runtime_set_has_no_forbidden_packages() -> None:
    # AC-1: License check is green for a repo whose runtime deps contain no
    # copyleft. The audited set is exactly the permissive runtime closure.
    packages = runtime_package_names(RUNTIME_EXPORT)
    assert "httpx" in packages
    assert "rich" in packages
    assert "pydantic" in packages
    assert "pydantic-settings" in packages
    # No dev-only tool leaked into the audited (runtime) set.
    assert all(name not in packages for name in DEV_ONLY_NAMES)


# ---------------------------------------------------------------------------
# AC-2: only runtime deps are audited; the dev dependency-group is excluded
# ---------------------------------------------------------------------------


def test_ac2_audited_command_scopes_to_runtime_packages_only() -> None:
    # AC-2: The license check audits ONLY runtime deps; the dev group is out of
    # scope. The pip-licenses command restricts the set via --packages.
    packages = runtime_package_names(RUNTIME_EXPORT)
    command = build_pip_licenses_command(packages)

    assert command[0] == "pip-licenses"
    assert "--packages" in command
    audited = command[command.index("--packages") + 1 :]
    assert audited == packages
    assert all(name not in audited for name in DEV_ONLY_NAMES)


def test_ac2_ci_step_syncs_and_runs_runtime_only() -> None:
    # AC-2: CI scopes the gate to runtime deps via --no-dev and the gate script.
    ci = _ci_yaml()
    assert "uv sync --no-dev --frozen" in ci
    assert "uv run --no-dev --with pip-licenses python tools/linters/license_gate.py" in ci


# ---------------------------------------------------------------------------
# AC-3: yamllint (GPL, dev-only) no longer fails the job and is not audited
# ---------------------------------------------------------------------------


def test_ac3_yamllint_excluded_from_audited_set() -> None:
    # AC-3: yamllint (GPL, dev-only) is not in the audited runtime set, so it
    # can no longer fail the job. It stays declared in [dependency-groups].dev.
    packages = runtime_package_names(RUNTIME_EXPORT)
    assert "yamllint" not in packages


def test_ac3_yamllint_still_declared_in_dev_group() -> None:
    # AC-3: yamllint is neither removed nor replaced; it remains a dev tool.
    pyproject = (_repo_root() / "pyproject.toml").read_text(encoding="utf-8")
    dev_section = pyproject.split("[dependency-groups]", 1)[1]
    assert "yamllint" in dev_section


# ---------------------------------------------------------------------------
# AC-4: a copyleft RUNTIME dependency still makes the gate fail
# ---------------------------------------------------------------------------


def test_ac4_copyleft_runtime_dependency_is_audited() -> None:
    # AC-4: If a copyleft dep is added to RUNTIME deps, it enters the audited
    # set and is therefore subject to --fail-on (job fails). Protection of the
    # distributed software is not weakened.
    packages = runtime_package_names(RUNTIME_EXPORT_WITH_COPYLEFT)
    assert "chardet" in packages

    command = build_pip_licenses_command(packages)
    audited = command[command.index("--packages") + 1 :]
    assert "chardet" in audited
    # The forbidden copyleft list is still applied to the audited set.
    assert "--fail-on" in command
    assert command[command.index("--fail-on") + 1] == build_fail_on()


# ---------------------------------------------------------------------------
# AC-5: the copyleft --fail-on list is unchanged; only the audited set narrows
# ---------------------------------------------------------------------------


def test_ac5_fail_on_list_is_unchanged() -> None:
    # AC-5: every AGPL/GPL/LGPL 3.0 variant (-only and -or-later) is preserved,
    # byte-for-byte identical to the historical pip-licenses --fail-on value.
    expected = (
        "AGPL-3.0;AGPL-3.0-only;AGPL-3.0-or-later;"
        "GPL-3.0;GPL-3.0-only;GPL-3.0-or-later;"
        "LGPL-3.0;LGPL-3.0-only;LGPL-3.0-or-later"
    )
    assert build_fail_on() == expected
    for family in ("AGPL-3.0", "GPL-3.0", "LGPL-3.0"):
        assert family in FORBIDDEN_LICENSES
        assert f"{family}-only" in FORBIDDEN_LICENSES
        assert f"{family}-or-later" in FORBIDDEN_LICENSES


def test_ac5_ci_step_does_not_inline_a_different_fail_on() -> None:
    # AC-5: the prohibited-license list lives in the gate module (single source
    # of truth); CI must not fork it by inlining the license list in a command.
    ci = _ci_yaml()
    assert build_fail_on() not in ci
    assert "AGPL-3.0;AGPL-3.0-only" not in ci


# ---------------------------------------------------------------------------
# AC-6: the CI step comment explains the runtime-only scope and why
# ---------------------------------------------------------------------------


def test_ac6_ci_comment_explains_runtime_only_scope() -> None:
    # AC-6: the step comment documents that the gate audits runtime-only and
    # why (dev tools are not distributed).
    ci = _ci_yaml()
    assert "RUNTIME deps only" in ci
    assert "never distributed" in ci
    assert "yamllint" in ci


# ---------------------------------------------------------------------------
# Parser robustness
# ---------------------------------------------------------------------------


def test_runtime_package_names_ignores_comments_blank_and_option_lines() -> None:
    export = "# header\n\nhttpx==0.28.1\n-e file:./pkg\n   # via x\nrich==15.0.0\n"
    assert runtime_package_names(export) == ["httpx", "rich"]


def test_runtime_package_names_strips_extras_and_markers() -> None:
    export = "httpx[brotli]==0.28.1 ; python_version >= '3.12'\n"
    assert runtime_package_names(export) == ["httpx"]
