"""Regenerate ``docs/generated/module-map.md`` — per-context layer map.

One row per *implemented* bounded context, showing which architectural layers
(D/A/I/X) carry code, the implementation line count, and the number of public
symbols. Replaces the seed ``(no modules yet)`` placeholder.

Shares the idempotent, timestamp-stable write strategy with
:mod:`update_state` so the Stop hook never churns the file.

Run from the repo root::

    python -m tools.verification.dump_module_map [--root PATH]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tools.verification.doc_render import (
    frontmatter_block,
    utc_timestamp,
    write_doc_if_changed,
)
from tools.verification.repo_scan import ModuleRow, gather_module_rows

__all__ = ["main", "render_module_map"]

_GENERATED_BY = "tools/verification/dump_module_map.py"
_LAST_UPDATED = "2026-06-04"
_OUTPUT_REL = Path("docs/generated/module-map.md")

_EMPTY_NOTE = (
    "_No bounded context has implementation files yet — every `apps/*` is "
    "scaffold-only (`.gitkeep`). Rows appear here as soon as a context gains "
    "real modules._ (AC-4)"
)


def _table(rows: list[ModuleRow]) -> str:
    header = [
        "| Context | Layers (D/A/I/X) | LoC | Public symbols |",
        "|---|---|---|---|",
    ]
    if not rows:
        return "\n".join(header) + "\n\n" + _EMPTY_NOTE
    body = [
        f"| {row.context} | {row.layers_cell()} | {row.loc} | {row.public_symbols} |"
        for row in rows
    ]
    return "\n".join(header + body)


def render_module_map(*, rows: list[ModuleRow], timestamp: str) -> str:
    """Render the complete ``module-map.md`` document for a given timestamp."""
    front = frontmatter_block(
        generated_by=_GENERATED_BY,
        timestamp=timestamp,
        last_updated=_LAST_UPDATED,
    )
    return f"""{front}
# Module map — auto-generated

> Auto-generated by `{_GENERATED_BY}` on every `Stop` hook. **Do not edit by
> hand** — changes are overwritten on the next regeneration.

{_table(rows)}

Legend: D=domain, A=application, I=infrastructure, X=interface. A `-` marks an
absent layer.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="dump-module-map",
        description="Regenerate docs/generated/module-map.md from the current tree.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root (default: inferred from this file's location).",
    )
    args = parser.parse_args(argv)
    root: Path = args.root.resolve()
    rows = gather_module_rows(root)

    def render(timestamp: str) -> str:
        return render_module_map(rows=rows, timestamp=timestamp)

    output = root / _OUTPUT_REL
    try:
        changed = write_doc_if_changed(output, render, timestamp=utc_timestamp())
    except OSError as exc:
        print(f"[dump_module_map] failed to write {output}: {exc}", file=sys.stderr)
        return 1

    status = "rewritten" if changed else "unchanged"
    print(f"[dump_module_map] {output.relative_to(root)} {status}.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
