"""Regenerate ``docs/generated/module-map.md`` from the working tree.

Emits one table row per bounded context under ``apps/`` showing which
architectural layers carry real code (D/A/I/X), the line count, and the number
of public symbols. This replaces the ``(no modules yet)`` seed placeholder with
honest per-context data.

Like :mod:`tools.verification.update_state`, the substantive body is a pure
function of the tree and the file is rewritten only when that body changes, so
the Stop hook does not churn it on every session (only ``last_generated_at`` /
``last_updated`` vary, and those are stripped before the comparison).
"""

from __future__ import annotations

import argparse
from datetime import UTC, datetime
from pathlib import Path

from tools.verification import repo_stats
from tools.verification.repo_stats import ContextStats

__all__ = ["main", "render_module_map", "write_module_map"]

_LAYER_ORDER: tuple[str, ...] = ("D", "A", "I", "X")


def _format_layers(present: tuple[str, ...]) -> str:
    if not present:
        return "—"
    return "/".join(code for code in _LAYER_ORDER if code in present)


def render_module_map(contexts: list[ContextStats], *, generated_at: datetime) -> str:
    """Render ``module-map.md``. ``generated_at`` must be timezone-aware UTC."""
    if generated_at.tzinfo is None:
        raise ValueError("generated_at must be timezone-aware UTC (GP-003)")
    generated_at = generated_at.astimezone(UTC)

    lines = [
        "---",
        "generated_by: tools/verification/dump_module_map.py",
        f"last_generated_at: {generated_at.isoformat()}",
        f"last_updated: {generated_at.date().isoformat()}",
        "---",
        "",
        "# Module map — auto-generated",
        "",
        "> Regenerated by `tools/verification/dump_module_map.py` on every "
        "`Stop` hook (`.claude/hooks/stop.sh`). One row per bounded context: "
        "layers present, line count, exposed public API. Do not edit by hand.",
        "",
        "| Context | Layers present (D/A/I/X) | LoC | Public symbols |",
        "|---|---|---|---|",
    ]
    if contexts:
        lines.extend(
            f"| {c.name} | {_format_layers(c.layers_present)} | {c.loc} | {c.public_symbols} |"
            for c in contexts
        )
    else:
        lines.append("| _(no contexts scaffolded)_ | — | 0 | 0 |")
    lines.extend(
        [
            "",
            "Legend: D=domain, A=application, I=infrastructure, X=interface. "
            "A layer is counted as present only when it contains non-trivial "
            "Python (an empty `__init__` or a scaffold placeholder does not "
            "count).",
            "",
        ]
    )
    return "\n".join(lines)


def _strip_volatile(text: str) -> str:
    kept = [
        line
        for line in text.splitlines()
        if not line.startswith(("last_generated_at:", "last_updated:"))
    ]
    return "\n".join(kept)


def write_module_map(
    path: Path,
    *,
    contexts: list[ContextStats],
    generated_at: datetime,
) -> bool:
    """Write ``module-map.md`` only when the substantive body changed."""
    new_text = render_module_map(contexts, generated_at=generated_at)
    if path.exists():
        old_text = path.read_text(encoding="utf-8")
        if _strip_volatile(old_text) == _strip_volatile(new_text):
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_text, encoding="utf-8", newline="\n")
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="dump_module_map",
        description="Regenerate docs/generated/module-map.md from the working tree.",
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="Repository root.")
    args = parser.parse_args(argv)

    repo_root: Path = args.root.resolve()
    contexts = repo_stats.collect_context_stats(repo_root)
    target = repo_root / "docs" / "generated" / "module-map.md"
    changed = write_module_map(target, contexts=contexts, generated_at=datetime.now(UTC))
    status = "rewritten" if changed else "unchanged (no substantive diff)"
    print(f"[dump_module_map] {target} {status}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
