"""Regenerate ``docs/generated/STATE.md`` — the "what exists today" snapshot.

``STATE.md`` is step 4 of ``AGENTS.md``: every agent reads it to learn the
current shape of the repo. Before NSG-50 it was a seed placeholder
(``last_generated_at: never (seed)``) that no step ever rewrote, so the DoD
box "STATE.md regenerated automatically via hook" was a false attestation.

This module closes that gap. It composes the static counts from
:mod:`repo_scan` with the volatile sections from :mod:`state_sources`, renders
the Markdown, and writes it only when the substantive content changed
(:func:`doc_render.write_doc_if_changed`) so the per-session Stop hook does not
churn the timestamp on every commit.

Run from the repo root::

    python -m tools.verification.update_state [--root PATH]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tools.verification import state_sources
from tools.verification.doc_render import (
    frontmatter_block,
    utc_timestamp,
    write_doc_if_changed,
)
from tools.verification.repo_scan import RepoStats, gather_stats
from tools.verification.state_sources import MergedPr, OpenQuestion

__all__ = ["build_state_md", "main", "render_state"]

_GENERATED_BY = "tools/verification/update_state.py"
_LAST_UPDATED = "2026-06-04"
_OUTPUT_REL = Path("docs/generated/STATE.md")

# Coverage is intentionally not computed here; see AC-2.
_COVERAGE_NOTE = (
    "> **Coverage is `n/a` by design.** A trustworthy figure needs a full "
    "instrumented `pytest --cov` run, which is too slow for the per-session "
    "Stop hook. Coverage is published separately by `dump_coverage.py` after "
    "CI (`docs/generated/coverage-by-module.md`). (AC-2)"
)


def _counts_table(stats: RepoStats) -> str:
    rows = [
        ("Bounded contexts (scaffolded)", str(stats.bounded_contexts_scaffolded)),
        ("Bounded contexts (implemented)", str(stats.bounded_contexts_implemented)),
        ("Domain entities", str(stats.domain_entities)),
        ("API endpoints", str(stats.api_endpoints)),
        ("Domain events defined", str(stats.domain_events)),
        ("Test functions", str(stats.test_functions)),
        ("Coverage", "n/a"),
    ]
    lines = ["| Item | Count |", "|---|---|"]
    lines.extend(f"| {item} | {count} |" for item, count in rows)
    return "\n".join(lines)


def _merged_prs_section(prs: list[MergedPr] | None) -> str:
    if prs is None:
        return "_Git history unavailable this run — section not refreshed._"
    if not prs:
        return "_None merged yet._"
    return "\n".join(
        f"- #{pr.number} — `{pr.source}` (merged {pr.merged_on})" for pr in prs
    )


def _open_questions_section(questions: list[OpenQuestion] | None) -> str:
    if questions is None:
        return "_Linear unavailable this run — Open Questions not refreshed (AC-7)._"
    if not questions:
        return "_None open._"
    return "\n".join(f"- {q.identifier} — {q.title}" for q in questions)


def _exec_plans_section(plans: list[str]) -> str:
    if not plans:
        return "_None active._"
    return "\n".join(f"- `{name}`" for name in plans)


def render_state(
    *,
    stats: RepoStats,
    prs: list[MergedPr] | None,
    questions: list[OpenQuestion] | None,
    plans: list[str],
    timestamp: str,
) -> str:
    """Render the complete ``STATE.md`` document for a given timestamp."""
    front = frontmatter_block(
        generated_by=_GENERATED_BY,
        timestamp=timestamp,
        last_updated=_LAST_UPDATED,
    )
    return f"""{front}
# State snapshot — auto-generated

> Auto-generated by `{_GENERATED_BY}` on every `Stop` hook. **Do not edit by
> hand** — changes are overwritten on the next regeneration.

## Counts

{_counts_table(stats)}

{_COVERAGE_NOTE}

## Recently merged PRs

{_merged_prs_section(prs)}

## Open Questions

{_open_questions_section(questions)}

## Active exec-plans

{_exec_plans_section(plans)}
"""


def build_state_md(root: Path) -> str:
    """Gather every source and render ``STATE.md`` (timestamp baked at render)."""
    return render_state(
        stats=gather_stats(root),
        prs=state_sources.recently_merged_prs(root),
        questions=state_sources.open_questions(),
        plans=state_sources.active_exec_plans(root),
        timestamp=utc_timestamp(),
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="update-state",
        description="Regenerate docs/generated/STATE.md from the current tree.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repository root (default: inferred from this file's location).",
    )
    args = parser.parse_args(argv)
    root: Path = args.root.resolve()

    stats = gather_stats(root)
    prs = state_sources.recently_merged_prs(root)
    questions = state_sources.open_questions()
    plans = state_sources.active_exec_plans(root)

    def render(timestamp: str) -> str:
        return render_state(
            stats=stats, prs=prs, questions=questions, plans=plans, timestamp=timestamp
        )

    output = root / _OUTPUT_REL
    try:
        changed = write_doc_if_changed(output, render, timestamp=utc_timestamp())
    except OSError as exc:
        print(f"[update_state] failed to write {output}: {exc}", file=sys.stderr)
        return 1

    status = "rewritten" if changed else "unchanged"
    print(f"[update_state] {output.relative_to(root)} {status}.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
